import pandas as pd
import pathlib
from typing import Union
import numpy as np
import matplotlib.pyplot as plt


class EAGanalysis:
    """
    Reads and analyzes data generated by the EAG experiment.
    Attributes: arrange data and analyze it (minus Blank and offset)
    """

    def __init__(self):

    def arrange_data(self, data_range):

            '''Takes pd.DataFrame and arrange the experiments in separate columns .
            Also slice the DataFrame (keeps only the time duration asked by the user)'''


    def transpose(self):

            '''Transposed the sliced dataframe, give it new index and data type'''



    def multi_indexing(self):



    def average_blank(self, blank_experiments):