import pandas as pd
import pathlib
from typing import Union
import numpy as np
import matplotlib.pyplot as plt


class EAGanalysis:
    """
    Reads and analyzes data generated by the EAG experiment.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):

        if type(data_fname) == str:
            data_fname = pathlib.Path(data_fname)
        if data_fname.is_file():
            self.data_fname = data_fname
        else:
            raise ValueError()

        self.data = pd.read_csv(self.data_fname, sep="\t", names=['Time', 'Value'])

    def arrange_data(self):

        Times = self.data.iloc[:, 0]

        Find_Signal = Times[Times.str.contains('Signal') == True]
        # returns all the places were the word signal is in
        Signal_index = Find_Signal.index
        # returns the indexes that self.data later be sliced by
        names = []
        # the next loop will slice the dataframe and split it into a list of data frames.
        # Each object in this list is an experiment
        for i, j in enumerate(Signal_index):
            names.append(i)
            if i < (len(Signal_index) - 1):
                names[i] = pd.DataFrame(self.data[Signal_index[i]:Signal_index[i + 1]])
                names[i].reset_index(drop=True, inplace=True)
            else:
                names[len(Signal_index) - 1] = pd.DataFrame(self.data[Signal_index[i]:])
                names[-1].reset_index(drop=True, inplace=True)

        Output = pd.concat(names, axis=1)
        # Combines all list objects into one dataframe

        del_Unnecessary_lines = Output.iloc[4:801]
        # delet all the lines after 800 (8 seconds)

        Transpose = del_Unnecessary_lines.transpose(copy=True)
        #Turns rows into columns and vise versa

        Transpose.columns = Transpose.iloc[0]
        #Assign row as column headers

        self.values_only = Transpose.drop(labels='Time')
        # leave only values in the data frame

        self.values_only = self.values_only.astype('float64')
        #Change data type from object to float.

    def multi_indexing(self):

        num_of_exp = []
        for i in range(1,(len(self.values_only)//3)+1):
            num_of_exp.append(i)

        index = pd.MultiIndex.from_product([num_of_exp, [1, 2,'D']],names=['#_of_experiment', 'Channel'])

        self.values_only = self.values_only.set_index(index)

    def average_blank(self):
        '''This function will create an average of the blank experiments and return it as pandas Series'''

        self.channel1_blank_avg = self.values_only.loc[((7,8,9), 1), slice(None)].mean()
        self.channel2_blank_avg = self.values_only.loc[((7,8,9), 2), slice(None)].mean()

        #Enter here the numbers of the blank experiments:
        # loc[((1st_blank,2nd_blank,3rd_blank,etc.), # of channel(1 or 2)), slice(None)]

    def minus_blank(self):
        '''This function will substract the blank experiments from all other experiments in the same channel'''
    # Not done!!!
        values_only4.subtract(channel2_blank_avg, axis=1, level=2)

    def plot_experiments(self):
        '''This function will plot all the experiments from the same channel in order to check for irregularities in the recordings '''

    def offset(self):
        '''This function will apply an offset on the data. this offset will take the first 100 samples,
        and subtrect its median from all the values of the same experiment'''

    def export_to_excel(self):
        self.values_only_1 = self.values_only.loc[(slice(None), 1), slice(None)]
        self.values_only_2 = self.values_only.loc[(slice(None), 2), slice(None)]

        with pd.ExcelWriter('Raw data - mix and segments, 12.5.21.xlsx') as writer:
            self.values_only.to_excel(writer, sheet_name='all_exp')
            self.values_only_1.to_excel(writer, sheet_name='channel1')
            self.values_only_2.to_excel(writer, sheet_name='channel2')
            self.channel1_blank_avg.to_excel(writer, sheet_name='channel1_blank_avg')
            self.channel2_blank_avg.to_excel(writer, sheet_name='channel2_blank_avg')

a= EAGanalysis('Raw data - mix and segments, 12.5.21.ASC')
a.arrange_data()
a.multi_indexing()
a.average_blank()
a.export_to_excel()


